<a href="https://colab.research.google.com/github/anvitank/Study-of-NumPy/blob/main/exp8_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 8
# Title: Tools for EDA- Numpy


In [7]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([[1,2,3],[4,5,6]])

print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [10]:
a.ndim

1

In [11]:
b.ndim

2

In [12]:
a.shape

(4,)

In [13]:
b.shape

(2, 3)

In [14]:
a.dtype

dtype('int64')

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
s=a+5
m=a*7
d=a/5
print(s)
print(m)
print(d)

[15 25 35 45]
[ 70 140 210 280]
[2. 4. 6. 8.]


In [27]:
np.mean(a)

np.float64(25.0)

In [28]:
np.median(a)

np.float64(25.0)

In [30]:
np.sum(a)

np.int64(100)